on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: unit-test
      run: python -m pytest -v

  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Publish
        with:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_PASS: ${{ secrets.GITHUB_PASS}}
        run: sh ./deploy_dockerhub.sh